# Generated by Django 5.1.4 on 2024-12-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='author',
            field=models.TextField(default=3, max_length=50, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
